"""cart constraints

Revision ID: 54d115e0bde3
Revises: c10ef697d06e
Create Date: 2025-12-14 10:02:52.712756

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '54d115e0bde3'
down_revision: Union[str, Sequence[str], None] = 'c10ef697d06e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart_items', 'cart_id', existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        'cart_items', 'product_id', existing_type=sa.INTEGER(), nullable=False
    )
    op.create_unique_constraint(
        'unique_cart_product', 'cart_items', ['cart_id', 'product_id']
    )
    op.drop_constraint(
        op.f('cart_items_product_id_fkey'), 'cart_items', type_='foreignkey'
    )
    op.create_foreign_key(
        None, 'cart_items', 'products', ['product_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(
        op.f('cart_items_product_id_fkey'),
        'cart_items',
        'products',
        ['product_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.drop_constraint('unique_cart_product', 'cart_items', type_='unique')
    op.alter_column(
        'cart_items', 'product_id', existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column('cart_items', 'cart_id', existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
