"""add cart and cart_items relations

Revision ID: c10ef697d06e
Revises: d6701eb114f9
Create Date: 2025-12-08 03:53:38.067953

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c10ef697d06e'
down_revision: Union[str, Sequence[str], None] = 'd6701eb114f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('price', sa.Integer(), nullable=False))
    op.drop_column('order_items', 'price_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'order_items',
        sa.Column('price_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column('order_items', 'price')
    # ### end Alembic commands ###
